name: super_app
description: main superapp
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  get: ^4.6.1
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  connectivity_plus: ^6.1.2
  dio: ^5.8.0+1
  go_router: ^14.7.2
  shared_preferences: ^2.5.1
  fluttertoast: ^8.2.11
  flash: ^3.1.1
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.4
  hugeicons: ^0.0.7
  flutter_svg: ^2.0.5
  country_code_picker: ^3.2.0
  shimmer: ^3.0.0
  equatable: ^2.0.7
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  timeline_tile: ^2.0.0
  pie_chart: ^5.4.0
  injectable: ^2.5.0
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.10.0
  carousel_slider: ^5.0.0
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.3
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  flutter_local_notifications_linux: ^5.0.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  crypto: ^3.0.3
  # loading
  loading_animation_widget: ^1.3.0
  # share
  share_plus: ^10.1.4
  # device info
  device_info_plus: ^11.0.0
  # package info
  package_info_plus: ^8.3.0
  #path
  path_provider: ^2.0.9
  # permission
  permission_handler: ^10.2.0
  # about errors
  sentry: ^8.14.1

  # get data about device
  app_links: ^6.4.0

  #animation library
  flutter_spinkit: ^5.1.0

  dots_indicator: ^2.1.0

  google_sign_in: ^5.3.3

  firebase_core: ^2.4.0

  firebase_messaging: ^14.1.4

  firebase_in_app_messaging: ^0.7.0+8

  firebase_auth: ^4.2.1

  cloud_firestore: ^4.2.0

  firebase_storage: ^11.0.8

  location: ^5.0.3

  image_picker: ^0.8.6
  photo_view: ^0.14.0

  sqflite: ^2.0.3+1

  flutter_verification_code: ^1.1.6

  agora_rtc_engine: ^6.1.0

  just_audio: ^0.9.46
  flutter_local_notifications: ^18.0.0
  flutter_facebook_auth: ^6.0.4
  url_launcher: ^6.1.6

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/Sound_Horizon.mp3
    - assets/audio_mixing/Agora.io-Interactions.mp3
    - assets/agora-logo.png
    - assets/dang.mp3
    - assets/ding.mp3
    - assets/gif.gif
    - assets/jpg.jpg
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Book.ttf
          weight: 400 # normal
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

