class RouteName {
  RouteName._();
  static const splash = 'splash';
  static const home = 'home';
  static const login = 'login';
  static const signup = 'signup';
  static const mainScreen = 'mainScreen';
  static const history = 'history';
  static const profile = 'profile';
  static const sendCash = 'sendCash';
  static const bankTransferCheckout = 'bankTransferCheckout';
  static const payment = 'payment';
  static const bankSelection = 'bankSelection';
  static const bankAmount = 'bankAmount';
  static const bankAccount = 'bankAccount';
  static const confirmTransfer = 'confirmTransfer';
  static const kachaAccount = 'kachaAccount';
  static const kachaAmount = 'kachaAmount';
  static const transactionDetail = 'transactionDetail';
  static const propertyDetail = 'propertyDetail';
  static const availableProperties = 'availableProperties';
  static const mortgageDashboard = 'mortgageDashboard';
  static const registrationScreen = 'registrationScreen';
  static const termsAndConditionsScreen = 'termsAndConditionsScreen';
  static const mobileTopup = 'mobileTopup';
  static const mobileTopupPhoneNumber = 'mobileTopupPhoneNumber';
  static const mobileTopupAmount = 'mobileTopupAmount';
  static const mobileTopupConfirmation = 'mobileTopupConfirmation';
  static const mobileTopupSuccess = 'mobileTopupSuccess';
}
